### ISSUE TITLE
Superpixel boundary code.

### ISSUE THREAD

**Issue by Zxl19990529** [panzhiyi/CC4S#1]
Hi~
Could you please provide the code for superpixel boundary generation ?

**Comment by panzhiyi** [comment]
We use the official SLIC code for matlab to generate superpixel boundaries. Please refer to [superpixels](https://ww2.mathworks.cn/help/images/ref/superpixels.html).

**Comment by Zxl19990529** [comment]
OK, thank you very much

**Comment by YINSONGHUI** [comment]
hello! what is the number of superpixels in the code?
